### ISSUE TITLE
How to "daemon and wallet"

### ISSUE THREAD

**Issue by Ossii** [SadBatman/cryptonote-sumokoin-pool#15]
Any documentation in regards to how to run the daemon and wallet-rpc?
Thinking about options that sets up a safe and correct environment.

Tried to use what I saw similar from the monero versions, but not all settings ar in the sumo wallet-rpc for example.
So some definitive pointers would be great.

**Comment by SadBatman** [comment]
./sumokoind --detach                                                             
./sumo-wallet-rpc --wallet-file=<wallet name> --rpc-bind-port <wallet port>      
<enter your wallet password>

When both are running it's worth to make sure the sumokoind has it's blockchain                                                                                     
synced. If this is not the case your pool will show errors with "Core is busy"   
until sumokoind is synchronized.

**Comment by Ossii** [comment]
simple as that ok, thanks :)

**Comment by SadBatman** [comment]
No problem!
