### ISSUE TITLE
Document pool SSL configuration

### ISSUE THREAD

**Issue by SadBatman** [SadBatman/cryptonote-sumokoin-pool#16]
We could use some clear instructions on how to enable SSL for a pool.  I'm not just talking about the pool ports (which is the most straight forward): it's mainly protecting the API and webserver with SSL that could use some instructions.

**Comment by yrjo** [comment]
I can write basic how-to in lets say SSL.md in root for combination:
 - lets encrypt
 - nginx
for api + web frontend
if you like..

**Comment by SadBatman** [comment]
That would be awesome! I can share my nginx config with you if you like.

**Comment by yrjo** [comment]
check that out ;) cheers

**Comment by SadBatman** [comment]
Awesome thanks again for the PR!
