### ISSUE TITLE
Pool dies - TypeError - SSL CRT KEY PATH in CONFIG

### ISSUE THREAD

**Issue by tlacicer** [SadBatman/cryptonote-sumokoin-pool#21]
any help would be appreciated - let me know what details are needed. ty

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at /home/tlacicer/pool/lib/pool.js:809:21
    at /home/tlacicer/pool/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/home/tlacicer/pool/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/home/tlacicer/pool/node_modules/async/lib/async.js:209:22)
    at startPoolServerTcp (/home/tlacicer/pool/lib/pool.js:714:11)
    at jobRefreshCompleteCallback (/home/tlacicer/pool/lib/pool.js:263:9)
    at /home/tlacicer/pool/lib/pool.js:232:17

**Comment by SadBatman** [comment]
Can you check if the path to your SSL certificate and key is correct ?

**Comment by tlacicer** [comment]
~/pool/ where init.js is

tlacicer@craig:~/pool$ ls -ltr
total 120
-rw-rw-r--   1 tlacicer tlacicer 17654 Dec 19 13:14 USAGE.md
-rw-rw-r--   1 tlacicer tlacicer  6062 Dec 19 13:14 redisBlocksUpgrade.js
-rw-rw-r--   1 tlacicer tlacicer  4764 Dec 19 13:14 README.md
-rw-rw-r--   1 tlacicer tlacicer 18025 Dec 19 13:14 LICENSE
-rw-rw-r--   1 tlacicer tlacicer  8230 Dec 19 13:14 init.js
drwxrwxr-x   2 tlacicer tlacicer  4096 Dec 19 13:14 email_templates
-rw-rw-r--   1 tlacicer tlacicer  1275 Dec 19 13:14 CREDITS.md
-rw-rw-r--   1 tlacicer tlacicer  5784 Dec 19 13:14 config_sumokoin.json
drwxrwxr-x   4 tlacicer tlacicer  4096 Dec 19 13:14 website
-rw-rw-r--   1 tlacicer tlacicer   684 Dec 19 13:16 package.json
drwxrwxr-x 180 tlacicer tlacicer  4096 Dec 19 13:17 node_modules
-rw-rw-r--   1 tlacicer tlacicer  5773 Dec 19 13:49 config.json
drwxrwxr-x   2 tlacicer tlacicer  4096 Dec 19 13:49 logs
drwxrwxr-x   2 tlacicer tlacicer  4096 Dec 19 13:59 lib
-rw-rw-r--   1 tlacicer tlacicer  1704 Dec 19 14:03 key.pem
-rw-rw-r--   1 tlacicer tlacicer  1269 Dec 19 14:03 cert.pem

**Comment by tlacicer** [comment]
the sample config lists port 5555 for both the ssl and nonssl port - however that still didn't correct the problem. I removed the ssl port configs and the server starts without issue - so it is ssl related.

**Comment by SadBatman** [comment]
Can you add this to the poolServer section in the config ?

        "sslKey": "key.pem",
        "sslCert": "cert.pem",

For some reason it was not in the config

**Comment by tlacicer** [comment]
yup .. looks good .. thank you
