### ISSUE TITLE
OOPS! Something went wrong: we haven't seen that IP for your sumo address

### ISSUE THREAD

**Issue by Ossii** [SadBatman/cryptonote-sumokoin-pool#23]
I get this error under settings when trying to add my email address.
I have checked that the pool is seeing my IP address correctly and copy&pasted directly from pool output in to the website.

Secondary question about the same functions: will user receive an email if a worker stops hashing?

**Comment by SadBatman** [comment]
Is this still an issue ? I think it just takes a bit time.

**Comment by Ossii** [comment]
I tried just now, still same error message

**Comment by mrtiritas** [comment]
Tested here, and it works.

Are you using any kind of load balancer? If so, change the proxy config var to True in the config,json file. It takes the IP address from x_forwarded_for instead of the IP.

**Comment by Ossii** [comment]
Nopes, no balancer. I see in the pool output that the IP where 3 of my miners run is showing.
Tried already to change that value to true before reporting, no change. hmmm...

**Comment by Ossii** [comment]
Tried again now to set `"trust_proxy_ip": true,` and let things run for a bit, still same.. weird....

**Comment by SadBatman** [comment]
Run:

redis-cli

And type:

keys Sumokoin:unique_workers:<your wallet address>

You will get results that contain IP addresses. Compare that against the IP you are trying to use in the settings page

**Comment by Ossii** [comment]
keys Sumokoin:unique_workers:* gives me a long list, with the IPs at the end of each line.
In this format:
399) "Sumokoin:unique_workers:Sumoo1Q****8832:713881729450076:**.110.**.178"
400) "Sumokoin:unique_workers:Sumoo1Q****8832:332507346710190:**.110.**.178"
401) "Sumokoin:unique_workers:Sumoo1Q****8832:159885451011359:**.110.**.178"
402) "Sumokoin:unique_workers:Sumoo1Q****8832:172472663759253:**.110.**.178"

So that does look good, but using the IP at the end there (which I can confirm is correcy) doesn't work in settings.

**Comment by corkapple** [comment]
Run:

redis-cli

And type:

keys Sumokoin:unique_workers:

- Nothing listed, is there something wrong with Redis config?

**Comment by Ossii** [comment]
Add a * at the end:
`keys Sumokoin:unique_workers:*`

**Comment by Ossii** [comment]
For me this is resolved. Did a clean install on a new host and just copied over the redis db.
For whatever reason now this also works
