### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by theminier** [SadBatman/cryptonote-sumokoin-pool#28]
Hi, 
i need some help. I feel like everything is almost complete

> 
> node init.js 
> 2018-01-02 01:26:36 [unlocker] Started
> 2018-01-02 01:26:36 [charts] Started
> 2018-01-02 01:26:36 [chartsDataCollector] Started
> 2018-01-02 01:26:36 [unlocker] No blocks candidates in redis
> 2018-01-02 01:26:36 [charts] Started
> 2018-01-02 01:26:36 [pool] (Thread 6) Blockchain height changed to 0, updating template.
> 2018-01-02 01:26:36 [payments] Started
> 2018-01-02 01:26:36 [payments] No workers' balances reached the minimum payment threshold
> 2018-01-02 01:26:36 [api] API started & listening on port 8118
> 2018-01-02 01:26:36 [pool] (Thread 1) Blockchain height changed to 0, updating template.
> 2018-01-02 01:26:37 [pool] (Thread 6) New block to mine at height 86720 w/ difficulty of 4445297356
> 2018-01-02 01:26:37 [pool] (Thread 10) Blockchain height changed to 0, updating template.
> 2018-01-02 01:26:37 [pool] (Thread 6) Started server listening on port 3333
> 2018-01-02 01:26:37 [pool] (Thread 3) Blockchain height changed to 0, updating template.
> 2018-01-02 01:26:37 [pool] (Thread 7) Blockchain height changed to 0, updating template.
> 2018-01-02 01:26:37 [api] Stat collection finished: 60 ms redis, 364 ms daemon
> 2018-01-02 01:26:37 [api] Broadcasting to 0 visitors and 0 address lookups
> 2018-01-02 01:26:37 [pool] (Thread 4) Blockchain height changed to 0, updating template.
> 2018-01-02 01:26:37 [pool] (Thread 2) Blockchain height changed to 0, updating template.
> 2018-01-02 01:26:37 [pool] (Thread 5) Blockchain height changed to 0, updating template.
> 2018-01-02 01:26:37 [pool] (Thread 6) Started server listening on port 4444
> 2018-01-02 01:26:37 [pool] (Thread 6) Started server listening on port 5555
> 2018-01-02 01:26:37 [pool] (Thread 6) Started server listening on port 6666
> 2018-01-02 01:26:37 [pool] (Thread 9) Blockchain height changed to 0, updating template.
> 2018-01-02 01:26:37 [master] Pool spawned on 40 thread(s)
> ....
> 2018-01-02 00:31:26 [unlocker] No blocks candidates in redis
> 2018-01-02 00:31:37 [api] Stat collection finished: 2 ms redis, 3 ms daemon
> 2018-01-02 00:31:37 [api] Broadcasting to 0 visitors and 0 address lookups
> 2018-01-02 00:31:56 [unlocker] No blocks candidates in redis
> 2018-01-02 00:31:56 [charts] hashrate chart collected value 0. Total sets count 1
> 2018-01-02 00:31:56 [charts] workers chart collected value 0. Total sets count 1
> 2018-01-02 00:31:57 [api] Stat collection finished: 1 ms redis, 2 ms daemon
> 2018-01-02 00:31:57 [api] Broadcasting to 0 visitors and 0 address lookups
> 2018-01-02 00:32:17 [api] Stat collection finished: 2 ms redis, 4 ms daemon
> 2018-01-02 00:32:17 [api] Broadcasting to 0 visitors and 0 address lookups
> 2018-01-02 00:32:26 [unlocker] No blocks candidates in redis
> 2018-01-02 00:32:37 [api] Stat collection finished: 3 ms redis, 4 ms daemon
> 2018-01-02 00:32:37 [api] Broadcasting to 0 visitors and 0 address lookups
> 2018-01-02 00:32:56 [unlocker] No blocks candidates in redis
> 2018-01-02 00:32:56 [charts] hashrate chart collected value 0. Total sets count 1
> 2018-01-02 00:32:56 [charts] workers chart collected value 0. Total sets count 1
> 2018-01-02 00:39:21 [pool] (Thread 4) New block to mine at height 86708 w/ difficulty of 4987115165
> 2018-01-02 00:39:22 [pool] (Thread 25) New block to mine at height 86708 w/ difficulty of 4987115165
> 2018-01-02 00:39:24 [pool] (Thread 10) Error polling getblockcount {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
> 2018-01-02 00:39:24 [pool] (Thread 10) Error polling getblockcount {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
> 2018-01-02 00:39:24 [pool] (Thread 34) New block to mine at height 86708 w/ difficulty of 4987115165
> 2018-01-02 00:39:25 [pool] (Thread 10) Error polling getblockcount {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
> 2018-01-02 00:39:25 [pool] (Thread 1) New block to mine at height 86708 w/ difficulty of 4987115165
> 2018-01-02 00:39:25 [pool] (Thread 24) Error polling getblockcount {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
> 2018-01-02 00:39:26 [pool] (Thread 10) Error polling getblockcount {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
> 2018-01-02 00:40:46 [pool] (Thread 8) Blockchain height changed to 86708, updating template.
> 2018-01-02 00:40:46 [pool] (Thread 6) Blockchain height changed to 86708, updating template.
> 
> TypeError: data.unshift is not a function
>     at global.log (/home/sumok/pool/lib/logger.js:48:14)
>     at log (/home/sumok/pool/lib/pool.js:28:12)
>     at /home/sumok/pool/lib/pool.js:207:13
>     at /home/sumok/pool/lib/apiInterfaces.js:58:9
>     at IncomingMessage.<anonymous> (/home/sumok/pool/lib/apiInterfaces.js:34:13)
>     at emitNone (events.js:72:20)
>     at IncomingMessage.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:905:12)
>     at nextTickCallbackWith2Args (node.js:441:9)
>     at process._tickCallback (node.js:355:17)
> 
> 2018-01-02 00:40:46 [pool] (Thread 24) Blockchain height changed to 86708, updating template.
> 2018-01-02 00:40:46 [pool] (Thread 13) Blockchain height changed to 86708, updating template.
> 2018-01-02 00:40:46 [pool] (Thread 20) Blockchain height changed to 86708, updating template.
> 2018-01-02 00:40:46 [pool] (Thread 23) Blockchain height changed to 86708, updating template.
> 2018-01-02 00:40:46 [pool] (Thread 18) Blockchain height changed to 86708, updating template.
> 
> TypeError: data.unshift is not a function
>     at global.log (/home/sumok/pool/lib/logger.js:48:14)
>     at log (/home/sumok/pool/lib/pool.js:28:12)
>     at /home/sumok/pool/lib/pool.js:207:13
>     at /home/sumok/pool/lib/apiInterfaces.js:58:9
>     at IncomingMessage.<anonymous> (/home/sumok/pool/lib/apiInterfaces.js:34:13)
>     at emitNone (events.js:72:20)
>     at IncomingMessage.emit (events.js:166:7)
>     at endReadableNT (_stream_readable.js:905:12)
>     at nextTickCallbackWith2Args (node.js:441:9)
>     at process._tickCallback (node.js:355:17)
> 

what am I doing wrong ?

also I succeeded to setup website, but it seems it can't connect to api.

also for "sumo-wallet-rpc --wallet-file=xxx", is it possible to run this as a daemon like sumokoind ?

finally, I can see "Pool spawned on 40 thread(s)" : is it possible to specify only 4 threads ?

thanks for help

**Comment by SadBatman** [comment]
Are you using node v4 or higher?

**Comment by theminier** [comment]
yes (v4.2.6)

**Comment by SadBatman** [comment]
```
2018-01-02 00:39:26 [pool] (Thread 10) Error polling getblockcount {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
```

Your daemon was not reachable.  Do you still have this problem?

**Comment by PalSec** [comment]
I had problem use wallet rpc like daemon too so I used command 'screen'
You install screen with command apt-get install screen on ubuntu then start command ' screen -Rd ', then window will open you , there you write command to start wallet rpc , next you use ctrl + a +d and
then check netstat -l if your port on wallet rpc is start...

**Comment by SadBatman** [comment]
Hey guys I'm going to close this as I assume this has been resolved. If not please reopen and I'll try to reply faster.
