### ISSUE TITLE
This pool is not healthy! Contact the admin for support. 

### ISSUE THREAD

**Issue by AhmedSh3ban** [SadBatman/cryptonote-sumokoin-pool#30]
everything run perfect but it keep say that 
This pool is not healthy! Contact the admin for support. at pool index

**Comment by SadBatman** [comment]
Check the monitoring tab on the admin page. Likely the wallet rpc server is not reachable.

**Comment by AhmedSh3ban** [comment]
thanks <3

**Comment by fmarines** [comment]
Hi,
got the same issue, everything works fine, but still saying This pool is not healthy! Contact the admin for support
