### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by Ingerulro** [SadBatman/cryptonote-sumokoin-pool#31]
Http://infinity-tech.ro:8117
API not working... Although I got no errors and init.js.... The pool hashes correctly but the website and API don't work. What am I doing wrong?

**Comment by Ingerulro** [comment]
I got this from pm2 logs

Connecting to 89.40.70.121 port 22, please wait...
login as: 
root@infinity-tech.ro's password: 
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 2.6.32-042stab120.19 x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Thu Jan  4 09:54:42 2018 from 5-15-75-218.residential.rdsnet.ro

root@infinity-tech:~# pm2 logs init
[TAILING] Tailing last 15 lines for [init] process (change the value with --lines option)
/root/.pm2/logs/init-error-0.log last 15 lines:
0|init     | TypeError: Cannot read property 'pool' of undefined
0|init     |     at /root/pool/lib/charts.js:148:30
0|init     |     at IncomingMessage. (/root/pool/lib/apiInterfaces.js:31:17)
0|init     |     at IncomingMessage.EventEmitter.emit (events.js:117:20)
0|init     |     at _stream_readable.js:920:16
0|init     |     at process._tickDomainCallback (node.js:459:13)
0|init     | TypeError: Object 16c1a3b7a6a5fe507923578796d68749c5b558074b9321e31e8966afa2029a6d has no method 'unshift'
0|init     |     at global.log (/root/pool/lib/logger.js:48:14)
0|init     |     at log (/root/pool/lib/pool.js:28:12)
0|init     |     at /root/pool/lib/pool.js:210:13
0|init     |     at /root/pool/lib/apiInterfaces.js:58:9
0|init     |     at IncomingMessage. (/root/pool/lib/apiInterfaces.js:34:13)
0|init     |     at IncomingMessage.EventEmitter.emit (events.js:117:20)
0|init     |     at _stream_readable.js:920:16
0|init     |     at process._tickDomainCallback (node.js:459:13)

/root/.pm2/logs/init-out-0.log last 15 lines:
0|init     | 2018-01-04 10:22:27 [pool] (Thread 2) Accepted valid share at difficulty 20000/29447 from Sumoo1SFrn4HM3EaY6FzADg8NSTKzmYcP3uTXbn8RVoEA6EAD6G3uNpLKBrCThCNnNPvFJ2QLN7eH4h8Mv56a6DFTfmvGBxS8S8@5.15.75.218
0|init     | 2018-01-04 10:22:44 [api] Stat collection finished: 2 ms redis, 3 ms daemon
0|init     | 2018-01-04 10:22:44 [api] Broadcasting to 0 visitors and 0 address lookups
0|init     | 2018-01-04 10:22:53 [unlocker] No blocks candidates in redis
0|init     | 2018-01-04 10:22:55 [pool] (Thread 2) Retargetting difficulty 20000 to 40000 for Sumoo1SFrn4HM3EaY6FzADg8NSTKzmYcP3uTXbn8RVoEA6EAD6G3uNpLKBrCThCNnNPvFJ2QLN7eH4h8Mv56a6DFTfmvGBxS8S8
0|init     | 2018-01-04 10:23:04 [api] Stat collection finished: 2 ms redis, 2 ms daemon
0|init     | 2018-01-04 10:23:04 [api] Broadcasting to 0 visitors and 0 address lookups
0|init     | 2018-01-04 10:23:23 [unlocker] No blocks candidates in redis
0|init     | 2018-01-04 10:23:23 [charts] hashrate chart collected value 113. Total sets count 27
0|init     | 2018-01-04 10:23:23 [charts] workers chart collected value 1. Total sets count 27
0|init     | 2018-01-04 10:23:24 [api] Stat collection finished: 1 ms redis, 2 ms daemon
0|init     | 2018-01-04 10:23:24 [api] Broadcasting to 0 visitors and 0 address lookups
0|init     | 2018-01-04 10:23:44 [api] Stat collection finished: 3 ms redis, 3 ms daemon
0|init     | 2018-01-04 10:23:44 [api] Broadcasting to 0 visitors and 0 address lookups
0|init     | 2018-01-04 10:23:53 [unlocker] No blocks candidates in redis

0|init     | 2018-01-04 10:24:04 [api] Stat collection finished: 2 ms redis, 3 ms daemon
0|init     | 2018-01-04 10:24:04 [api] Broadcasting to 0 visitors and 0 address lookups

**Comment by cryptobender69** [comment]
@Ingerulro did you find the solution for this?
