### ISSUE TITLE
Error json

### ISSUE THREAD

**Issue by Ingerulro** [SadBatman/cryptonote-sumokoin-pool#38]
2018-01-12 02:08:19 (Thread 2) Error polling getb
lockcount {"code":-32603,"message":"JsonValue typ
e is not ARRAY or OBJECT"}

I am using leviarcoind not sumokoind... Any ideas?

**Comment by SadBatman** [comment]
Maybe your coin does not have getblockcount. Perhaps you need to disable authentication on the daemon ?

I'm sorry but I can't help you with this.
