### ISSUE TITLE
Forked for another coin... Miner cannot login

### ISSUE THREAD

**Issue by Ingerulro** [SadBatman/cryptonote-sumokoin-pool#41]
I Forked for another crypto but I cannot seem to figure out what adress prefix to use....
My addresses start with eu... Ease help with decimal code for eu

**Comment by SadBatman** [comment]
Could you ping me on telegram ? @sadbatman ?

If you have another coin then I can also make a repo specific for your coin so all the Sumokoin specific wording/icons can be replaced.  To fix the address prefix I - can you give me a full wallet address ?

**Comment by leisegang** [comment]
How do i get this pool to work with STELLITE?
uint64_t const CRYPTONOTE_PUBLIC_ADDRESS_BASE58_PREFIX = 0x2419;

I only get "INVALID ADDRESS USED"

Se2VMQMwYHu2e4QTDrZf7biGeBSVLV6zqSNjks9VGbPtSFuemoEuu7DVEsB8TKEpjeUUKhMnQu1BthUETvDziD2S1M8DDTjSa

i believe that "Se" is the default.
