### ISSUE TITLE
Estimated Round Status bar ? 

### ISSUE THREAD

**Issue by AhmedSh3ban** [SadBatman/cryptonote-sumokoin-pool#45]
first best regards , Sadbatman 
your last update was epic " Current Block Effort "

i saw many mining pools use cryptonote-universal-pool with new features
Estimated Round Status 

http://nbr.4miner.me
http://pool.ultranote.org

- this is a  new feature ?

**Comment by bet0x** [comment]
They are doing it on a simple way, you can just copy paste their javascript:
`
var datacur = new Date() - new Date(parseInt(lastStats.pool.lastBlockFound));
--
  | $("#elapsedroundtime").html(new Date(datacur).toISOString().split("T")[1].split(".")[0]);
`

Just download the file http://pool.ultranote.org/pages/home.html and start to hack!

**Comment by SadBatman** [comment]
Correct! It's actually a simple change that was added a week ago.

**Comment by leisegang** [comment]
THANKs for letting me see how easy it was to borrow code from the pool pages 👯
