### ISSUE TITLE
sumo-walelt-rpc

### ISSUE THREAD

**Issue by PalSec** [SadBatman/cryptonote-sumokoin-pool#48]
Hi,

I can`t start sumo-wallet-rpc like daemon...When I close window where I started command sumo-wallet-rpc so Wallet not work....Thanks for help...

**Comment by Ossii** [comment]
run it in screen for example? as in screen -Rd wallet , then start the sumo-wallet-rpc
ctrl+a+d to get out, screen -Rd wallet to get back in

**Comment by PalSec** [comment]
Thanks....command is working but system write me error now: 
{"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
