### ISSUE TITLE
Wallet-rpc-error

### ISSUE THREAD

**Issue by PalSec** [SadBatman/cryptonote-sumokoin-pool#49]
HI,

I have problem with sending sumokoin...My rpc wallet write me this error:
2018-Jan-27 08:51:05.875479 [RPC0]selected transfers: 
2018-Jan-27 08:51:06.094531 [RPC0]amount=36.524153700, real_output=6, real_output_in_tx_index=0, indexes: 259021 383065 419830 565377 592068 754260 756214 756982 757603 761727 761801 762236 762537 
2018-Jan-27 08:51:06.187280 [RPC0]selected transfers: 
2018-Jan-27 08:51:06.187753 [RPC0]amount=36.524153700, real_output=6, real_output_in_tx_index=0, indexes: 259021 383065 419830 565377 592068 754260 756214 756982 757603 761727 761801 762236 762537 
2018-Jan-27 08:51:06.357227 [RPC0]ERROR /root/sumokoin/src/wallet/wallet2.cpp:3297 daemon_send_resp.status != CORE_RPC_STATUS_OK. THROW EXCEPTION: error::tx_rejected
2018-Jan-27 08:51:06.357908 [RPC0]/root/sumokoin/src/wallet/wallet2.cpp:3297:N5tools5error11tx_rejectedE: transaction was rejected by daemon, status = Failed, tx:

Thanks for answer

**Comment by SadBatman** [comment]
It seems your sumokoind daemon was busy with something else. Perhaps syncing ?
