### ISSUE TITLE
Fixing malformed address in Redis

### ISSUE THREAD

**Issue by bomb-on** [SadBatman/cryptonote-sumokoin-pool#52]
Before introducing the `allowedMinerAddressPrefixes` in my config, I got 2 miners connected with malformed addresses. They actually mined some coins but of course that now they cannot be paid out. Is there a simple way to change this records in Redis into proper address and make that payment go through?

Thanks a lot!

**Comment by mattcode55** [comment]
Try `del <coin>:workers:<address>` in redis-cli

**Comment by bomb-on** [comment]
@mattcode55 Thank you very much kind sir!
